import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import "flowbite";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // You can customize these
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${dmSans.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
